"""Generate one Markdown file per Minecraft biome (as of 1.21)."""

import os
from pathlib import Path

BIOMES = [
    # ── Overworld ──────────────────────────────────────────────────────────
    {
        "name": "Plains",
        "dimension": "Overworld",
        "category": "Temperate",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "A flat, open biome covered in grass with occasional oak trees and tall grass. One of the most common biomes and a frequent spawn location for new players.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Oak Wood", "Flowers", "Seeds (from grass)"],
        "passive_mobs": ["Cow", "Sheep", "Pig", "Chicken", "Horse", "Donkey", "Rabbit"],
        "neutral_mobs": ["Wolf (rare)"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider", "Witch", "Pillager"],
        "structures": ["Village", "Pillager Outpost", "Ruined Portal"],
    },
    {
        "name": "Sunflower Plains",
        "dimension": "Overworld",
        "category": "Temperate",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "A plains variant blanketed with sunflowers — the only natural source of yellow dye. Identical gameplay to plains, but visually distinct.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Oak Wood", "Sunflower", "Flowers"],
        "passive_mobs": ["Cow", "Sheep", "Pig", "Chicken", "Horse"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider"],
        "structures": ["Village", "Pillager Outpost"],
    },
    {
        "name": "Forest",
        "dimension": "Overworld",
        "category": "Temperate",
        "temperature": 0.7,
        "precipitation": "Rain",
        "description": "A dense biome filled with oak and birch trees. Wolves and mushrooms can be found here, and it's an excellent early-game source of wood.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Oak Wood", "Birch Wood", "Mushrooms", "Apples"],
        "passive_mobs": ["Cow", "Sheep", "Pig", "Chicken", "Rabbit"],
        "neutral_mobs": ["Wolf"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider", "Witch"],
        "structures": ["Ruined Portal"],
    },
    {
        "name": "Flower Forest",
        "dimension": "Overworld",
        "category": "Temperate",
        "temperature": 0.7,
        "precipitation": "Rain",
        "description": "A rarer forest variant bursting with every type of flower. A great source of dyes and a honey hotspot due to abundant bee nests.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["All Flower Types", "Oak Wood", "Birch Wood", "Honeycomb"],
        "passive_mobs": ["Cow", "Sheep", "Rabbit", "Bee"],
        "neutral_mobs": ["Bee"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider"],
        "structures": ["Ruined Portal"],
    },
    {
        "name": "Birch Forest",
        "dimension": "Overworld",
        "category": "Temperate",
        "temperature": 0.6,
        "precipitation": "Rain",
        "description": "A forest dominated by birch trees with a clean, white-bark aesthetic. Birch wood is plentiful here.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Birch Wood", "Mushrooms"],
        "passive_mobs": ["Cow", "Sheep", "Pig", "Chicken", "Rabbit"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider"],
        "structures": [],
    },
    {
        "name": "Old Growth Birch Forest",
        "dimension": "Overworld",
        "category": "Temperate",
        "temperature": 0.6,
        "precipitation": "Rain",
        "description": "A birch forest variant featuring unusually tall birch trees, giving it a cathedral-like canopy. Harder to navigate but yields more birch wood.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Birch Wood (large quantities)"],
        "passive_mobs": ["Cow", "Sheep", "Rabbit"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider"],
        "structures": [],
    },
    {
        "name": "Dark Forest",
        "dimension": "Overworld",
        "category": "Temperate",
        "temperature": 0.7,
        "precipitation": "Rain",
        "description": "A dense, foreboding forest of dark oak and mushroom trees whose canopy blocks most sunlight. Hostile mobs can spawn during the day here.",
        "surface_blocks": ["Grass Block", "Dirt", "Mycelium (patches)", "Stone"],
        "notable_resources": ["Dark Oak Wood", "Brown/Red Mushrooms", "Apples"],
        "passive_mobs": ["Cow", "Pig", "Sheep"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider", "Witch", "Phantom (night)"],
        "structures": ["Woodland Mansion"],
    },
    {
        "name": "Swamp",
        "dimension": "Overworld",
        "category": "Swamp",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "A murky biome with waterlogged terrain, lily pads, and blue orchids. Home to witches and slimes, it has a distinctive gloomy atmosphere.",
        "surface_blocks": ["Grass Block", "Dirt", "Clay", "Water", "Mud"],
        "notable_resources": ["Clay", "Lily Pad", "Blue Orchid", "Slimeball"],
        "passive_mobs": ["Frog", "Turtle (rare)", "Rabbit"],
        "neutral_mobs": ["Slime (full moon nights)"],
        "hostile_mobs": ["Witch", "Zombie", "Skeleton", "Slime"],
        "structures": ["Witch Hut", "Ruined Portal"],
    },
    {
        "name": "Mangrove Swamp",
        "dimension": "Overworld",
        "category": "Swamp",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "A swamp variant introduced in 1.19, filled with mangrove trees growing in shallow water. Frogs, fireflies, and mud abound.",
        "surface_blocks": ["Mud", "Muddy Mangrove Roots", "Grass Block", "Water"],
        "notable_resources": ["Mangrove Wood", "Mangrove Propagule", "Mud", "Mud Bricks"],
        "passive_mobs": ["Frog", "Tropical Fish", "Bat"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Drowned", "Slime"],
        "structures": [],
    },
    {
        "name": "Jungle",
        "dimension": "Overworld",
        "category": "Jungle",
        "temperature": 0.95,
        "precipitation": "Rain",
        "description": "A lush, densely vegetated biome with massive jungle trees, vines, cocoa pods, and melons. The only place parrots and ocelots naturally spawn.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone", "Podzol"],
        "notable_resources": ["Jungle Wood", "Cocoa Beans", "Melon", "Bamboo", "Vines"],
        "passive_mobs": ["Ocelot", "Parrot", "Chicken", "Pig", "Cow"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Spider", "Creeper"],
        "structures": ["Jungle Temple"],
    },
    {
        "name": "Sparse Jungle",
        "dimension": "Overworld",
        "category": "Jungle",
        "temperature": 0.95,
        "precipitation": "Rain",
        "description": "A jungle edge biome with fewer large trees and more open ground. Easier to traverse than a full jungle while still containing jungle-specific loot.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Jungle Wood", "Cocoa Beans", "Melon", "Bamboo"],
        "passive_mobs": ["Ocelot", "Parrot", "Chicken", "Pig"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Spider", "Creeper"],
        "structures": ["Jungle Temple (rare)"],
    },
    {
        "name": "Bamboo Jungle",
        "dimension": "Overworld",
        "category": "Jungle",
        "temperature": 0.95,
        "precipitation": "Rain",
        "description": "A jungle variant packed with bamboo and panda spawns. Bamboo is the primary fuel and resource here.",
        "surface_blocks": ["Grass Block", "Dirt", "Podzol", "Stone"],
        "notable_resources": ["Bamboo", "Jungle Wood", "Melon"],
        "passive_mobs": ["Panda", "Parrot", "Ocelot", "Chicken"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Spider", "Creeper"],
        "structures": ["Jungle Temple (rare)"],
    },
    {
        "name": "Savanna",
        "dimension": "Overworld",
        "category": "Savanna",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "A warm, dry biome with acacia trees and tall grass. Never rains here. Villages are common, and llamas roam the plateau variants.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone", "Red Sand (patches)"],
        "notable_resources": ["Acacia Wood", "Dead Bush", "Gravel"],
        "passive_mobs": ["Cow", "Sheep", "Pig", "Chicken", "Horse", "Donkey"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider", "Pillager"],
        "structures": ["Village", "Pillager Outpost", "Ruined Portal"],
    },
    {
        "name": "Savanna Plateau",
        "dimension": "Overworld",
        "category": "Savanna",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "Elevated savanna terrain forming flat-topped mesa-like hills. Llamas spawn here and the views are stunning.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone", "Acacia Leaves"],
        "notable_resources": ["Acacia Wood"],
        "passive_mobs": ["Llama", "Cow", "Sheep"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider"],
        "structures": [],
    },
    {
        "name": "Windswept Savanna",
        "dimension": "Overworld",
        "category": "Savanna",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "A dramatic variant of the savanna with jagged, overhanging cliffs and floating islands. Extremely difficult terrain to build on.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone", "Gravel"],
        "notable_resources": ["Acacia Wood", "Stone"],
        "passive_mobs": ["Llama", "Cow", "Sheep"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider"],
        "structures": [],
    },
    {
        "name": "Desert",
        "dimension": "Overworld",
        "category": "Dry",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "Vast sandy biome with no passive animal spawns, cacti, and dead bushes. Villages, temples, and wells dot the landscape.",
        "surface_blocks": ["Sand", "Sandstone", "Hardened Sandstone"],
        "notable_resources": ["Sand", "Sandstone", "Cactus", "Dead Bush", "Gold (from temples)"],
        "passive_mobs": ["Rabbit"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider", "Husk"],
        "structures": ["Desert Temple", "Desert Village", "Desert Well", "Pillager Outpost", "Ruined Portal"],
    },
    {
        "name": "Badlands",
        "dimension": "Overworld",
        "category": "Dry",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "A striking biome of red sand and terracotta cliffs layered with many colors. Gold ore generates at higher elevations than elsewhere.",
        "surface_blocks": ["Red Sand", "Terracotta (all colors)", "Hardened Clay", "Stone"],
        "notable_resources": ["Terracotta (all colors)", "Red Sand", "Gold Ore (elevated)", "Dead Bush"],
        "passive_mobs": ["Rabbit"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider", "Husk"],
        "structures": ["Mineshaft (exposed on surface)"],
    },
    {
        "name": "Wooded Badlands",
        "dimension": "Overworld",
        "category": "Dry",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "The top plateaus of badlands terrain sport coarse dirt and oak trees, creating a strange forest-over-clay aesthetic.",
        "surface_blocks": ["Coarse Dirt", "Grass Block", "Terracotta", "Red Sand"],
        "notable_resources": ["Terracotta", "Oak Wood", "Gold Ore"],
        "passive_mobs": ["Rabbit", "Cow"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Husk"],
        "structures": ["Mineshaft (exposed on surface)"],
    },
    {
        "name": "Eroded Badlands",
        "dimension": "Overworld",
        "category": "Dry",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "The most dramatic badlands variant, featuring tall, narrow terracotta spires rising from the red sand floor. Rare and visually iconic.",
        "surface_blocks": ["Red Sand", "Terracotta (all colors)", "Stone"],
        "notable_resources": ["Terracotta", "Red Sand", "Gold Ore"],
        "passive_mobs": ["Rabbit"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Husk", "Creeper"],
        "structures": [],
    },
    {
        "name": "Taiga",
        "dimension": "Overworld",
        "category": "Cold",
        "temperature": 0.25,
        "precipitation": "Rain",
        "description": "A cold forest of spruce trees with wolves, foxes, and sweet berry bushes. Villages and outposts appear here as well.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone", "Coarse Dirt"],
        "notable_resources": ["Spruce Wood", "Sweet Berries", "Fern"],
        "passive_mobs": ["Wolf", "Fox", "Rabbit", "Cow", "Sheep", "Pig"],
        "neutral_mobs": ["Wolf"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider", "Witch"],
        "structures": ["Village", "Pillager Outpost", "Ruined Portal"],
    },
    {
        "name": "Old Growth Pine Taiga",
        "dimension": "Overworld",
        "category": "Cold",
        "temperature": 0.3,
        "precipitation": "Rain",
        "description": "A taiga variant with extra-large spruce trees covered in podzol beneath their canopy. Wolves, foxes, and mushrooms are common.",
        "surface_blocks": ["Podzol", "Coarse Dirt", "Grass Block", "Moss"],
        "notable_resources": ["Spruce Wood (large)", "Podzol", "Mushrooms"],
        "passive_mobs": ["Wolf", "Fox", "Rabbit"],
        "neutral_mobs": ["Wolf"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider"],
        "structures": [],
    },
    {
        "name": "Old Growth Spruce Taiga",
        "dimension": "Overworld",
        "category": "Cold",
        "temperature": 0.25,
        "precipitation": "Rain",
        "description": "A darker taiga variant with very large spruce trees. The canopy is denser than the pine variant and podzol covers much of the ground.",
        "surface_blocks": ["Podzol", "Coarse Dirt", "Grass Block"],
        "notable_resources": ["Spruce Wood (large)", "Podzol", "Mushrooms"],
        "passive_mobs": ["Wolf", "Fox", "Rabbit"],
        "neutral_mobs": ["Wolf"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Spider"],
        "structures": [],
    },
    {
        "name": "Snowy Taiga",
        "dimension": "Overworld",
        "category": "Snowy",
        "temperature": -0.5,
        "precipitation": "Snow",
        "description": "A cold taiga permanently blanketed in snow. Spruce trees, foxes, and wolves populate this frigid biome.",
        "surface_blocks": ["Snow Block", "Grass Block (under snow)", "Dirt", "Stone"],
        "notable_resources": ["Spruce Wood", "Snow", "Ice"],
        "passive_mobs": ["Wolf", "Fox", "Rabbit", "Cow", "Sheep"],
        "neutral_mobs": ["Wolf"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Stray"],
        "structures": ["Village (snowy style)", "Pillager Outpost"],
    },
    {
        "name": "Snowy Plains",
        "dimension": "Overworld",
        "category": "Snowy",
        "temperature": 0.0,
        "precipitation": "Snow",
        "description": "A flat, snow-covered biome with sparse trees and frozen water. Strays replace some skeletons here. Villages are rare but possible.",
        "surface_blocks": ["Snow Block", "Grass Block (under snow)", "Dirt", "Ice"],
        "notable_resources": ["Snow", "Ice", "Packed Ice (rivers)"],
        "passive_mobs": ["Rabbit", "Polar Bear", "Cow", "Sheep", "Pig"],
        "neutral_mobs": ["Polar Bear"],
        "hostile_mobs": ["Zombie", "Skeleton", "Stray", "Creeper"],
        "structures": ["Snowy Village", "Igloos"],
    },
    {
        "name": "Ice Spikes",
        "dimension": "Overworld",
        "category": "Snowy",
        "temperature": 0.0,
        "precipitation": "Snow",
        "description": "A dramatic snowy biome covered in packed ice spires. No villages generate here, but packed ice is abundant.",
        "surface_blocks": ["Snow Block", "Packed Ice Spikes", "Ice"],
        "notable_resources": ["Packed Ice", "Snow", "Ice"],
        "passive_mobs": ["Rabbit", "Polar Bear"],
        "neutral_mobs": ["Polar Bear"],
        "hostile_mobs": ["Zombie", "Skeleton", "Stray"],
        "structures": [],
    },
    {
        "name": "Snowy Beach",
        "dimension": "Overworld",
        "category": "Snowy",
        "temperature": 0.05,
        "precipitation": "Snow",
        "description": "A frozen beach where sand meets snow and the water is iced over. Very sparse and mostly a transition biome.",
        "surface_blocks": ["Sand", "Snow", "Ice", "Gravel"],
        "notable_resources": ["Sand", "Snow", "Ice"],
        "passive_mobs": ["Rabbit"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Stray", "Drowned"],
        "structures": [],
    },
    {
        "name": "Meadow",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "Gently sloping mountain valleys filled with wildflowers, tall grass, and occasional trees. Bees and donkeys are common here.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Flowers (all types)", "Oak Wood", "Honey"],
        "passive_mobs": ["Sheep", "Cow", "Rabbit", "Donkey", "Bee"],
        "neutral_mobs": ["Bee"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper"],
        "structures": ["Pillager Outpost (rare)", "Ruined Portal"],
    },
    {
        "name": "Cherry Grove",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "Introduced in 1.20, this biome features stunning pink cherry blossom trees with petal particle effects. Exclusive source of cherry wood.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Cherry Wood", "Cherry Petals", "Pink Petals (ground)"],
        "passive_mobs": ["Sheep", "Cow", "Rabbit", "Bee", "Pig"],
        "neutral_mobs": ["Bee"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper"],
        "structures": [],
    },
    {
        "name": "Grove",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": -0.2,
        "precipitation": "Snow",
        "description": "A snow-covered valley filled with spruce trees and powder snow traps. Wolves and rabbits inhabit this cold grove.",
        "surface_blocks": ["Snow Block", "Powder Snow", "Dirt", "Stone"],
        "notable_resources": ["Spruce Wood", "Powder Snow", "Snow"],
        "passive_mobs": ["Rabbit", "Wolf"],
        "neutral_mobs": ["Wolf"],
        "hostile_mobs": ["Zombie", "Skeleton", "Stray"],
        "structures": [],
    },
    {
        "name": "Snowy Slopes",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": -0.3,
        "precipitation": "Snow",
        "description": "Mid-elevation mountain terrain permanently covered in snow and powder snow. Goats roam these steep slopes.",
        "surface_blocks": ["Snow Block", "Powder Snow", "Stone", "Gravel"],
        "notable_resources": ["Powder Snow", "Snow", "Stone", "Gravel"],
        "passive_mobs": ["Goat", "Rabbit"],
        "neutral_mobs": ["Goat"],
        "hostile_mobs": ["Zombie", "Skeleton", "Stray"],
        "structures": ["Igloo (rare)"],
    },
    {
        "name": "Jagged Peaks",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": -0.7,
        "precipitation": "Snow",
        "description": "The highest, sharpest mountain peaks composed of stone and snowcapped summits. Goats leap between the jagged formations.",
        "surface_blocks": ["Stone", "Snow Block", "Gravel"],
        "notable_resources": ["Stone", "Iron Ore", "Emerald Ore", "Snow"],
        "passive_mobs": ["Goat"],
        "neutral_mobs": ["Goat"],
        "hostile_mobs": ["Zombie", "Skeleton", "Stray"],
        "structures": [],
    },
    {
        "name": "Frozen Peaks",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": -0.7,
        "precipitation": "Snow",
        "description": "High mountain peaks made almost entirely of packed ice and snow. Extremely treacherous terrain with beautiful icy vistas.",
        "surface_blocks": ["Packed Ice", "Snow Block", "Ice", "Stone"],
        "notable_resources": ["Packed Ice", "Snow", "Ice", "Stone"],
        "passive_mobs": ["Goat"],
        "neutral_mobs": ["Goat"],
        "hostile_mobs": ["Zombie", "Skeleton", "Stray"],
        "structures": [],
    },
    {
        "name": "Stony Peaks",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": 1.0,
        "precipitation": "Rain",
        "description": "Warm mountain peaks made of calcite and gravel rather than snow. Found in warmer climates, these peaks have a more rocky, earthy tone.",
        "surface_blocks": ["Stone", "Calcite", "Gravel", "Dirt"],
        "notable_resources": ["Stone", "Calcite", "Gravel", "Emerald Ore", "Iron Ore"],
        "passive_mobs": ["Goat"],
        "neutral_mobs": ["Goat"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper"],
        "structures": [],
    },
    {
        "name": "Windswept Hills",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": 0.2,
        "precipitation": "Rain",
        "description": "Rolling highland terrain with sparse trees and exposed stone. Formerly called 'Extreme Hills', this biome is rich in emeralds and infested stone.",
        "surface_blocks": ["Grass Block", "Stone", "Gravel", "Dirt"],
        "notable_resources": ["Stone", "Emerald Ore", "Iron Ore", "Infested Stone"],
        "passive_mobs": ["Llama", "Goat", "Sheep"],
        "neutral_mobs": ["Goat"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Silverfish"],
        "structures": ["Ruined Portal", "Pillager Outpost"],
    },
    {
        "name": "Windswept Gravelly Hills",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": 0.2,
        "precipitation": "Rain",
        "description": "A gravelly variant of windswept hills where gravel replaces most surface dirt and grass. Sparse vegetation and rugged terrain.",
        "surface_blocks": ["Gravel", "Stone", "Grass Block (patches)"],
        "notable_resources": ["Gravel", "Stone", "Emerald Ore"],
        "passive_mobs": ["Llama", "Goat", "Sheep"],
        "neutral_mobs": ["Goat"],
        "hostile_mobs": ["Zombie", "Skeleton", "Silverfish"],
        "structures": [],
    },
    {
        "name": "Windswept Forest",
        "dimension": "Overworld",
        "category": "Mountain",
        "temperature": 0.2,
        "precipitation": "Rain",
        "description": "A forested version of windswept hills, with both the tree density of a forest and the dramatic elevation changes of mountain terrain.",
        "surface_blocks": ["Grass Block", "Dirt", "Stone"],
        "notable_resources": ["Oak Wood", "Spruce Wood", "Stone", "Emerald Ore"],
        "passive_mobs": ["Llama", "Goat", "Sheep", "Wolf"],
        "neutral_mobs": ["Wolf", "Goat"],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Silverfish"],
        "structures": [],
    },
    {
        "name": "Beach",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "Sandy shores at the edge of oceans. Turtles lay eggs here at night. A source of sand, gravel, and buried treasure.",
        "surface_blocks": ["Sand", "Gravel", "Sandstone"],
        "notable_resources": ["Sand", "Gravel", "Buried Treasure"],
        "passive_mobs": ["Turtle"],
        "neutral_mobs": [],
        "hostile_mobs": ["Drowned", "Zombie", "Skeleton"],
        "structures": ["Buried Treasure"],
    },
    {
        "name": "Stony Shore",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.2,
        "precipitation": "Rain",
        "description": "Rocky coastal biome formed where mountains meet the sea. No sand — just stone and gravel meeting the water.",
        "surface_blocks": ["Stone", "Gravel", "Cobblestone"],
        "notable_resources": ["Stone", "Gravel", "Buried Treasure (rare)"],
        "passive_mobs": [],
        "neutral_mobs": [],
        "hostile_mobs": ["Drowned", "Zombie", "Skeleton"],
        "structures": [],
    },
    {
        "name": "River",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "Narrow water channels carving through the landscape. Salmon and squid swim here, and clay is plentiful on the riverbed.",
        "surface_blocks": ["Water", "Sand", "Gravel", "Clay", "Dirt"],
        "notable_resources": ["Clay", "Gravel", "Sand", "Salmon"],
        "passive_mobs": ["Salmon", "Squid"],
        "neutral_mobs": [],
        "hostile_mobs": ["Drowned"],
        "structures": [],
    },
    {
        "name": "Frozen River",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.0,
        "precipitation": "Snow",
        "description": "A river biome in cold climates where the water surface is frozen over with ice. Salmon still swim beneath.",
        "surface_blocks": ["Ice", "Snow", "Gravel", "Dirt", "Clay"],
        "notable_resources": ["Ice", "Clay", "Snow"],
        "passive_mobs": ["Salmon"],
        "neutral_mobs": [],
        "hostile_mobs": ["Drowned", "Stray"],
        "structures": [],
    },
    {
        "name": "Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "The standard deep ocean biome with kelp forests, sea grass, and ocean monuments. Guardians and elder guardians patrol monuments.",
        "surface_blocks": ["Water", "Sand", "Gravel", "Clay (deep)"],
        "notable_resources": ["Kelp", "Sea Grass", "Prismarine (from monuments)", "Sponge", "Cod"],
        "passive_mobs": ["Cod", "Salmon", "Squid", "Dolphin"],
        "neutral_mobs": ["Dolphin"],
        "hostile_mobs": ["Drowned", "Guardian (near monument)"],
        "structures": ["Ocean Monument", "Shipwreck", "Buried Treasure"],
    },
    {
        "name": "Deep Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "Deeper waters with ocean monuments and more hostile guardians. The trenches go much lower than standard ocean floors.",
        "surface_blocks": ["Water", "Sand", "Gravel"],
        "notable_resources": ["Prismarine", "Sea Lantern", "Gold (from monuments)", "Sponge"],
        "passive_mobs": ["Cod", "Squid"],
        "neutral_mobs": ["Dolphin"],
        "hostile_mobs": ["Drowned", "Guardian", "Elder Guardian"],
        "structures": ["Ocean Monument", "Shipwreck"],
    },
    {
        "name": "Cold Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "A colder ocean biome with a gravel seabed and kelp forests. Salmon are more common here than cod.",
        "surface_blocks": ["Water", "Gravel", "Sand"],
        "notable_resources": ["Kelp", "Salmon", "Gravel"],
        "passive_mobs": ["Salmon", "Squid", "Dolphin"],
        "neutral_mobs": ["Dolphin"],
        "hostile_mobs": ["Drowned"],
        "structures": ["Shipwreck", "Ruins"],
    },
    {
        "name": "Deep Cold Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "A deeper variant of the cold ocean. Ocean monuments can generate here, patrolled by guardians.",
        "surface_blocks": ["Water", "Gravel"],
        "notable_resources": ["Kelp", "Prismarine", "Salmon"],
        "passive_mobs": ["Salmon", "Squid"],
        "neutral_mobs": [],
        "hostile_mobs": ["Drowned", "Guardian"],
        "structures": ["Ocean Monument", "Shipwreck"],
    },
    {
        "name": "Lukewarm Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "A warm-ish ocean with a sandy floor, coral reefs, and tropical fish. More visually diverse than a cold ocean.",
        "surface_blocks": ["Water", "Sand", "Dirt", "Clay"],
        "notable_resources": ["Coral", "Tropical Fish", "Kelp", "Sea Grass"],
        "passive_mobs": ["Pufferfish", "Tropical Fish", "Squid", "Dolphin"],
        "neutral_mobs": ["Pufferfish", "Dolphin"],
        "hostile_mobs": ["Drowned"],
        "structures": ["Shipwreck", "Ruins"],
    },
    {
        "name": "Deep Lukewarm Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "A deeper version of the lukewarm ocean. Ocean monuments spawn here, and the sandy trenches stretch far down.",
        "surface_blocks": ["Water", "Sand"],
        "notable_resources": ["Coral", "Prismarine", "Sponge"],
        "passive_mobs": ["Tropical Fish", "Squid"],
        "neutral_mobs": ["Dolphin"],
        "hostile_mobs": ["Drowned", "Guardian"],
        "structures": ["Ocean Monument", "Shipwreck"],
    },
    {
        "name": "Warm Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 1.0,
        "precipitation": "Rain",
        "description": "The warmest ocean with vibrant coral reefs, sea pickles, and tropical fish. No kelp grows here, but coral is exclusive to this biome.",
        "surface_blocks": ["Water", "Sand", "Coral", "Sea Pickle"],
        "notable_resources": ["Coral (all types)", "Sea Pickle", "Tropical Fish", "Sponge"],
        "passive_mobs": ["Pufferfish", "Tropical Fish", "Squid"],
        "neutral_mobs": ["Pufferfish"],
        "hostile_mobs": ["Drowned"],
        "structures": ["Shipwreck", "Ruins"],
    },
    {
        "name": "Frozen Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.0,
        "precipitation": "Snow",
        "description": "An icy ocean biome with surface ice and iceberg formations. Polar bears and strays lurk among the frozen terrain.",
        "surface_blocks": ["Ice", "Snow Block", "Water (beneath ice)", "Gravel"],
        "notable_resources": ["Ice", "Packed Ice (icebergs)", "Blue Ice (icebergs)", "Snow"],
        "passive_mobs": ["Salmon", "Squid", "Polar Bear"],
        "neutral_mobs": ["Polar Bear"],
        "hostile_mobs": ["Drowned", "Stray"],
        "structures": ["Shipwreck", "Ruins"],
    },
    {
        "name": "Deep Frozen Ocean",
        "dimension": "Overworld",
        "category": "Aquatic",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "The deep version of frozen ocean. Despite the name, the water is not frozen at depth. Icebergs still form and ocean monuments can appear.",
        "surface_blocks": ["Water", "Gravel", "Sand"],
        "notable_resources": ["Prismarine", "Ice (icebergs)"],
        "passive_mobs": ["Salmon", "Squid"],
        "neutral_mobs": [],
        "hostile_mobs": ["Drowned", "Guardian"],
        "structures": ["Ocean Monument", "Shipwreck"],
    },
    {
        "name": "Mushroom Fields",
        "dimension": "Overworld",
        "category": "Rare",
        "temperature": 0.9,
        "precipitation": "Rain",
        "description": "An island biome of mycelium with giant mushrooms and mooshrooms. Hostile mobs never spawn naturally here, making it a safe haven.",
        "surface_blocks": ["Mycelium", "Dirt"],
        "notable_resources": ["Brown Mushroom", "Red Mushroom", "Mushroom Stew (from mooshrooms)"],
        "passive_mobs": ["Mooshroom"],
        "neutral_mobs": [],
        "hostile_mobs": [],
        "structures": [],
    },
    {
        "name": "Dripstone Caves",
        "dimension": "Overworld",
        "category": "Cave",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "An underground cave biome filled with stalagmites and stalactites of pointed dripstone. Drowned can spawn in the underground pools.",
        "surface_blocks": ["Stone", "Pointed Dripstone", "Dripstone Block", "Water", "Lava"],
        "notable_resources": ["Pointed Dripstone", "Dripstone Block", "Copper Ore", "Iron Ore"],
        "passive_mobs": ["Bat"],
        "neutral_mobs": [],
        "hostile_mobs": ["Zombie", "Skeleton", "Creeper", "Drowned (water pools)", "Cave Spider"],
        "structures": [],
    },
    {
        "name": "Lush Caves",
        "dimension": "Overworld",
        "category": "Cave",
        "temperature": 0.5,
        "precipitation": "Rain",
        "description": "A vibrant underground biome with moss, spore blossoms, azalea trees above ground, glow berries, and axolotls in the underground pools.",
        "surface_blocks": ["Moss Block", "Moss Carpet", "Clay", "Water", "Glow Berries"],
        "notable_resources": ["Glow Berries", "Moss Block", "Spore Blossom", "Dripleaf", "Axolotl"],
        "passive_mobs": ["Axolotl", "Glow Squid", "Tropical Fish", "Bat"],
        "neutral_mobs": ["Axolotl"],
        "hostile_mobs": ["Zombie", "Skeleton", "Cave Spider"],
        "structures": [],
    },
    {
        "name": "Deep Dark",
        "dimension": "Overworld",
        "category": "Cave",
        "temperature": 0.8,
        "precipitation": "Rain",
        "description": "The deepest and most dangerous cave biome, found below Y=0. Home to the Warden — the strongest hostile mob. Sculk blocks and Ancient Cities generate here.",
        "surface_blocks": ["Sculk", "Sculk Catalyst", "Sculk Sensor", "Sculk Shrieker", "Deepslate"],
        "notable_resources": ["Sculk (all variants)", "Echo Shard", "Swift Sneak Enchantment (from chests)", "Reinforced Deepslate"],
        "passive_mobs": [],
        "neutral_mobs": [],
        "hostile_mobs": ["Warden"],
        "structures": ["Ancient City"],
    },
    # ── Nether ─────────────────────────────────────────────────────────────
    {
        "name": "Nether Wastes",
        "dimension": "Nether",
        "category": "Nether",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "The default Nether biome: a hellscape of netherrack, lava seas, and ghast-filled skies. Nether fortresses and quartz ore are the main draws.",
        "surface_blocks": ["Netherrack", "Gravel", "Lava", "Soul Sand (patches)"],
        "notable_resources": ["Nether Quartz", "Nether Gold Ore", "Magma Block", "Glowstone"],
        "passive_mobs": ["Strider (lava)"],
        "neutral_mobs": ["Zombie Piglin", "Enderman"],
        "hostile_mobs": ["Ghast", "Blaze (fortress)", "Wither Skeleton (fortress)", "Magma Cube"],
        "structures": ["Nether Fortress", "Ruined Portal", "Bastion Remnant"],
    },
    {
        "name": "Crimson Forest",
        "dimension": "Nether",
        "category": "Nether",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "A blood-red forest of crimson fungi and huge nether fungi trees. Hoglins provide meat and leather, while piglins patrol aggressively.",
        "surface_blocks": ["Crimson Nylium", "Crimson Stem", "Netherrack", "Crimson Roots", "Shroomlight"],
        "notable_resources": ["Crimson Stem (wood)", "Crimson Fungi", "Shroomlight", "Weeping Vines"],
        "passive_mobs": ["Hoglin", "Strider"],
        "neutral_mobs": ["Piglin", "Zombified Piglin"],
        "hostile_mobs": ["Piglin Brute"],
        "structures": ["Bastion Remnant"],
    },
    {
        "name": "Warped Forest",
        "dimension": "Nether",
        "category": "Nether",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "A teal-hued forest of warped fungi and spore-filled air. The only Nether biome where Hoglins refuse to spawn. Endermen are abundant.",
        "surface_blocks": ["Warped Nylium", "Warped Stem", "Netherrack", "Warped Roots", "Warped Wart Block"],
        "notable_resources": ["Warped Stem (wood)", "Warped Fungi", "Shroomlight", "Twisting Vines"],
        "passive_mobs": ["Strider"],
        "neutral_mobs": ["Enderman"],
        "hostile_mobs": [],
        "structures": ["Bastion Remnant (rare)"],
    },
    {
        "name": "Soul Sand Valley",
        "dimension": "Nether",
        "category": "Nether",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "A pale, foggy biome of soul sand and soul soil, scattered with fossils and blue fire. Skeletons and ghasts fill the eerie silence.",
        "surface_blocks": ["Soul Sand", "Soul Soil", "Bone Block", "Basalt"],
        "notable_resources": ["Soul Sand", "Soul Soil", "Bone Block", "Soul Fire", "Basalt"],
        "passive_mobs": [],
        "neutral_mobs": [],
        "hostile_mobs": ["Skeleton", "Ghast", "Enderman"],
        "structures": ["Ruined Portal", "Nether Fortress (rare)"],
    },
    {
        "name": "Basalt Deltas",
        "dimension": "Nether",
        "category": "Nether",
        "temperature": 2.0,
        "precipitation": "None",
        "description": "A volcanic biome of basalt columns and blackstone formations rising from lava. Magma cubes swarm in huge numbers.",
        "surface_blocks": ["Basalt", "Blackstone", "Magma Block", "Lava", "Netherrack"],
        "notable_resources": ["Basalt", "Blackstone", "Gilded Blackstone", "Magma Cream"],
        "passive_mobs": ["Strider"],
        "neutral_mobs": [],
        "hostile_mobs": ["Magma Cube (large numbers)", "Ghast"],
        "structures": [],
    },
    # ── End ─────────────────────────────────────────────────────────────────
    {
        "name": "The End",
        "dimension": "End",
        "category": "End",
        "temperature": 0.5,
        "precipitation": "None",
        "description": "The central End island floating in the void, home to the Ender Dragon boss fight. The obsidian pillars topped with End Crystals must be destroyed to defeat the dragon.",
        "surface_blocks": ["End Stone", "Obsidian Pillars", "Bedrock (fountain)"],
        "notable_resources": ["End Stone", "Dragon Egg (one-time)", "Elytra (via End Cities)", "End Crystal"],
        "passive_mobs": [],
        "neutral_mobs": ["Enderman"],
        "hostile_mobs": ["Ender Dragon"],
        "structures": ["End Fountain (obsidian)", "End Portal (return)"],
    },
    {
        "name": "Small End Islands",
        "dimension": "End",
        "category": "End",
        "temperature": 0.5,
        "precipitation": "None",
        "description": "Tiny islands of end stone scattered through the outer End void. Chorus plants dot the surface and endermen roam freely.",
        "surface_blocks": ["End Stone"],
        "notable_resources": ["Chorus Fruit", "End Stone"],
        "passive_mobs": [],
        "neutral_mobs": ["Enderman"],
        "hostile_mobs": [],
        "structures": [],
    },
    {
        "name": "End Midlands",
        "dimension": "End",
        "category": "End",
        "temperature": 0.5,
        "precipitation": "None",
        "description": "Medium-sized outer End islands with chorus plants. End Cities can spawn here, offering Shulker boxes and Elytra.",
        "surface_blocks": ["End Stone"],
        "notable_resources": ["Chorus Fruit", "End Stone", "Purpur Block", "Shulker Shell", "Elytra"],
        "passive_mobs": [],
        "neutral_mobs": ["Enderman"],
        "hostile_mobs": ["Shulker"],
        "structures": ["End City", "End Ship (with Elytra)"],
    },
    {
        "name": "End Highlands",
        "dimension": "End",
        "category": "End",
        "temperature": 0.5,
        "precipitation": "None",
        "description": "The elevated terrain of the outer End islands where End Cities most commonly generate. Prime destination for Elytra hunters.",
        "surface_blocks": ["End Stone"],
        "notable_resources": ["Purpur Block", "End Rod", "Shulker Shell", "Elytra", "Chorus Fruit"],
        "passive_mobs": [],
        "neutral_mobs": ["Enderman"],
        "hostile_mobs": ["Shulker"],
        "structures": ["End City", "End Ship (most common here)"],
    },
    {
        "name": "End Barrens",
        "dimension": "End",
        "category": "End",
        "temperature": 0.5,
        "precipitation": "None",
        "description": "Flat outer End islands with no chorus plants and no structures. A quiet, empty expanse of end stone with only endermen.",
        "surface_blocks": ["End Stone"],
        "notable_resources": ["End Stone"],
        "passive_mobs": [],
        "neutral_mobs": ["Enderman"],
        "hostile_mobs": [],
        "structures": [],
    },
]


def slugify(name: str) -> str:
    return name.lower().replace(" ", "_").replace("(", "").replace(")", "").replace("'", "")


def render(biome: dict) -> str:
    passive = ", ".join(biome["passive_mobs"]) or "None"
    neutral = ", ".join(biome["neutral_mobs"]) or "None"
    hostile = ", ".join(biome["hostile_mobs"]) or "None"
    surface = ", ".join(biome["surface_blocks"])
    resources = ", ".join(biome["notable_resources"])
    structures = ", ".join(biome["structures"]) or "None"

    precip_icon = {"Rain": "Rain", "Snow": "Snow", "None": "None (dry)"}[biome["precipitation"]]

    return f"""# {biome["name"]}

{biome["description"]}

## Overview

| Field         | Value                       |
|---------------|-----------------------------|
| Dimension     | {biome["dimension"]}        |
| Category      | {biome["category"]}         |
| Temperature   | {biome["temperature"]}      |
| Precipitation | {precip_icon}               |

## Blocks & Resources

**Surface / Terrain Blocks:** {surface}

**Notable Resources:** {resources}

## Mobs

| Type     | Mobs                        |
|----------|-----------------------------|
| Passive  | {passive}                   |
| Neutral  | {neutral}                   |
| Hostile  | {hostile}                   |

## Structures

{structures}
"""


def main():
    base = Path(__file__).parent / "minecraft-biomes"
    for biome in BIOMES:
        dim_dir = base / biome["dimension"].lower().replace(" ", "_")
        dim_dir.mkdir(parents=True, exist_ok=True)
        file_path = dim_dir / f"{slugify(biome['name'])}.md"
        file_path.write_text(render(biome))
        print(f"  wrote {file_path.relative_to(Path(__file__).parent)}")
    print(f"\nDone — {len(BIOMES)} biome files created.")


if __name__ == "__main__":
    main()
